name: Deploy Dev PR

on:
  workflow_dispatch:
  push:
    branches: [ git-workflow ]

jobs:

  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0 # We need a complete history for merging branches
      - uses: andyoknen/combine-pull-requests@v1
        with:
          label: deploy.dev
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare merged repo
        run: |
          mkdir /tmp/repo
          rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /tmp/repo
          cd /tmp/repo
          tar czf /tmp/repo.tgz ./
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: repo.tgz
          path: /tmp/repo.tgz

#  deploy-pre:
#    needs: merge
#    runs-on: gui
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: repo.tgz
#      - name: Prepare
#        run: |
#          mkdir ./repo
#          tar xzf repo.tgz -C ./repo/
#          cd ./repo
#          npm i
#          npm run minimize:bastyon
#      - name: Copy to dest dir
#        run: rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /docker/pre/

  deploy-test:
    needs: merge
    runs-on: gui
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Prepare
        run: |
          mkdir ./repo
          tar xzf repo.tgz -C ./repo/
          cd ./repo
          npm i
          npm run minimize:bastyon:test
      - name: Copy to dest dir
        run: rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /docker/gui/
