name: Deploy Dev PR

on:
  workflow_dispatch:
  push:
    branches: [ git-workflow ]

jobs:

  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - uses: andyoknen/combine-pull-requests@v2
        with:
          label: deploy.dev
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare merged repo
        run: |
          mkdir /tmp/repo
          rsync -ah --exclude={'.git/','.github/','node_modules/'} ./ /tmp/repo
          cd /tmp/repo
          tar czf /tmp/repo.tgz ./
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo.tgz
          path: /tmp/repo.tgz
