name: Deploy Dev PR

on:
  workflow_dispatch:
  push:
    branches: [ git-workflow ]

jobs:

  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0 # We need a complete history for merging branches
      - uses: andyoknen/combine-pull-requests@v1
        with:
          label: deploy.dev
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive merged repo
        run: |
          mkdir -p /tmp/repo
          rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /tmp/repo/
          cd /tmp/repo
          tar czf /tmp/repo.tgz ./
      - name: Upload artifact repo.tgz
        uses: actions/upload-artifact@v1
        with:
          name: repo.tgz
          path: /tmp/repo.tgz
      - name: Archive merged proxy repo
        run: |
          mkdir -p /tmp/proxy
          cd ./proxy16
          rsync -ah ./ /tmp/proxy/
          cd /tmp/proxy
          tar czf /tmp/proxy.tgz ./
      - name: Upload artifact proxy.tgz
        uses: actions/upload-artifact@v1
        with:
          name: proxy.tgz
          path: /tmp/proxy.tgz

  deploy-pre:
    needs: merge
    runs-on: gui
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Prepare
        run: |
          mkdir -p ./repo
          tar xzf repo.tgz -C ./repo/
          cd ./repo
          npm i
          npm run minimize:bastyon
      - name: Copy to dest dir
        run: rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /docker/pre/

  deploy-test:
    needs: merge
    runs-on: gui
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Prepare
        run: |
          mkdir -p ./repo
          tar xzf repo.tgz -C ./repo/
          cd ./repo
          npm i
          npm run minimize:bastyon:test
      - name: Copy to dest dir
        run: rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /docker/gui/

  build-proxy:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: proxy.tgz
      - name: Prepare
        run: |
          mkdir -p ./repo
          tar xzf proxy.tgz -C ./repo/
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/proxy
          tags: type=raw,value=night
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./repo/
          file: ./repo/dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-proxy:
    needs: build-proxy
    runs-on: proxy.test
    steps:
      - name: Pull && Up proxy container
        run: /data/proxy_pre_pull_up.sh
        shell: bash
      - name: Reset nginx cache
        run: /data/reset_cache.sh
        shell: bash

  deploy-proxy-test:
    needs: build-proxy
    runs-on: proxy.test
    steps:
      - name: Pull && Up proxy container
        run: /data/proxy_test_pull_up.sh
        shell: bash
      - name: Reset nginx cache
        run: /data/reset_cache.sh
        shell: bash