name: Deploy to night.bastyon.com

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Save HEAD information
        run: git --no-pager log --decorate=short --pretty=oneline -n1 > head.txt
      - name: Archive repo
        run: |
          mkdir -p /tmp/repo
          rsync -ah --exclude={'.git','.gitignore','.github','node_modules','.well-known'} ./ /tmp/repo/
          cd /tmp/repo
          tar czf /tmp/repo.tgz ./
      - name: Upload artifact repo.tgz
        uses: actions/upload-artifact@v3
        with:
          name: repo.tgz
          path: /tmp/repo.tgz
      - name: Save artifact head.txt
        uses: actions/upload-artifact@v3
        with:
          name: head
          path: ./head.txt

  build-macos:
    needs: prepare
    runs-on: macos-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: repo.tgz
      - name: Unpack artifact
        run: tar xzf repo.tgz
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare building
        run: |
          npm i
          npm run dev:bastyon -- -sha=${{ github.sha }}
      - name: Prepare for app notarization
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
          echo '${{ secrets.APPLECERT }}' | base64 -d > applecert.p12
      - name: Building
        env:
          APPLE_API_KEY: './applecert.p12'
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
          CSC_LINK: 'file://applecert.p12'
          CSC_KEY_PASSWORD: ${{ secrets.APPLECERTPWD }}
        run: |
          npm run distm
          ls -lh ./dist/
      - name: Show logs
        if: always()
        run: |
          cat notarization-error.log
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ./dist/BastyonSetup.dmg
