name: Detect PRs conflicts

on: pull_request

jobs:
  build:
    name: potential-conflicts-checker
    runs-on: ubuntu-latest
    steps:
      - uses: andyoknen/potential-conflicts-checker-action@v1
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}